workspace:
  base: /test
  path: ecl-twig-loader

services:
  web:
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    environment:
      - DOCUMENT_ROOT=/test/ecl-twig-loader

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  composer-update-lowest:
    group: post-prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      - composer update --prefer-lowest --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  grumphp:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/phpunit

matrix:
  PHP_VERSION:
    - 7.2
    - 7.3
  COMPOSER_BOUNDARY:
    - lowest
    - highest
